### ISSUE TITLE
Make RSS feeds autodiscoverable

### ISSUE THREAD

**Issue by martey** [TrackMaven/TrackMaven.github.io#59]
The blog should use [feed autodiscovery](https://blog.whatwg.org/feed-autodiscovery) to make it easier for people to subscribe (since they will be able to just plug in the blog's URL into their feed reader, instead of searching for the feed).

I completely missed the RSS link in the footer and would have assumed that there were no feeds available if I hadn't realized that the site was hosted on Github Pages, tracked down the repository, and then read #21.

**Comment by joshfinnie** [comment]
@martey thanks for the heads up! I haven't dealt much with RSS feeds that weren't just given to me like in WordPress. I will add the autodiscovery today!

**Comment by joshfinnie** [comment]
@martey this change should be out there, do you see the RSS link now? I am not sure what I am looking for...

**Comment by martey** [comment]
Yes, it worked! Thanks.
