### ISSUE TITLE
Bridging the Docker Container Gap: Setting up Linux to share IPs like OS X

### ISSUE THREAD

**Issue by joshfinnie** [TrackMaven/TrackMaven.github.io#65]
Being a split OS company, we run into some interesting issues, one big one was the difference in how OS X and Linux handle linked Docker containers.

**Comment by joshfinnie** [comment]
@mlcamilli any interest in writing this blog post before I remove you as assignee and move it to the backlog?

**Comment by mlcamilli** [comment]
We were never able to do this so....

**Comment by joshfinnie** [comment]
:cry:
