### ISSUE TITLE
2015 Year In Review

### ISSUE THREAD

**Issue by joshfinnie** [TrackMaven/TrackMaven.github.io#80]
Another http://engineroom.trackmaven.com/blog/2014-year-in-review/

**Comment by softinio** [comment]
Should we mention anything about skipper and/or coreos for microservices?

**Comment by joshfinnie** [comment]
@softinio we could, I really like to tie it back to posts we wrote throughout the year, but it might be difficult to get everything out there just based on posts made. We also don't want to over promise ;-)

**Comment by fheisler** [comment]
Closing as probably too outdated now :(

**Comment by joshfinnie** [comment]
6 more days @fheisler...

![screen shot 2016-02-04 at 1 47 49 pm](https://cloud.githubusercontent.com/assets/125098/12825777/ee5837c0-cb45-11e5-9c87-04b24334bd3e.png)
